### ISSUE TITLE
Method of pushing to GitHub

### ISSUE THREAD

**Issue by BaffledJimmy** [leostat/rtfm#78]
Hi,

I've got some commands that I'd like to push into the database, but am having a few problems working out how to do it.  Do I make the changes in my local copy and then push the _entire_ db back up to git via commit / push?

If you throw together a quick how-to or similar I've got a fair few to add :)

Jim

**Comment by leostat** [comment]
Working on that now! Re working the readme to make it a bit nicer :)!

(Ps thanks!)

**Comment by leostat** [comment]
Closing as updated the readme with (hopefully) better info
