### ISSUE TITLE
terminaltables - kali

### ISSUE THREAD

**Issue by rowbot1** [leostat/rtfm#84]
Terminaltables installed but rtfm wont run it
<pre><span style="background-color:#2E3436"> </span><span style="background-color:#2E3436"><font color="#CC0000">✘ </font></span><span style="background-color:#2E3436"><font color="#C4A000">⚡ </font></span><span style="background-color:#3465A4"><font color="#2E3436"> /opt/terminaltables </font></span><span style="background-color:#4E9A06"><font color="#3465A4"></font></span><span style="background-color:#4E9A06"><font color="#2E3436">  master </font></span><font color="#4E9A06"></font> <font color="#4E9A06">pip</font> install <u style="text-decoration-style:single">terminaltables</u>                                                                           

<font color="#C4A000">DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won&apos;t be maintained after that date. A future version of pip will drop support for Python 2.7.</font>
Requirement already satisfied: terminaltables in /usr/local/lib/python2.7/dist-packages (3.1.0)
<span style="background-color:#2E3436"> </span><span style="background-color:#2E3436"><font color="#C4A000">⚡ </font></span><span style="background-color:#3465A4"><font color="#2E3436"> /opt/terminaltables </font></span><span style="background-color:#4E9A06"><font color="#3465A4"></font></span><span style="background-color:#4E9A06"><font color="#2E3436">  master </font></span><font color="#4E9A06"></font> <font color="#4E9A06">rtfm</font> -e x11 -pP           
<font color="#FCE94F"><b>[WARNING]: </b></font>Unable to have pretty output,  Please &apos;pip install terminaltables&apos; or remove these lines :)
Traceback (most recent call last):
  File &quot;/opt/rtfm/rtfm.py&quot;, line 786, in &lt;module&gt;
    run()
  File &quot;/opt/rtfm/rtfm.py&quot;, line 149, in run
    Search(conn, sqlcmd, sqltpl, sqllst)
  File &quot;/opt/rtfm/rtfm.py&quot;, line 171, in Search
    PrintThing(cmd)
  File &quot;/opt/rtfm/rtfm.py&quot;, line 599, in PrintThing
    table = AsciiTable(table_data)
NameError: name &apos;AsciiTable&apos; is not defined
<span style="background-color:#2E3436"> </span><span style="background-color:#2E3436"><font color="#CC0000">✘ </font></span><span style="background-color:#2E3436"><font color="#C4A000">⚡ </font></span><span style="background-color:#3465A4"><font color="#2E3436"> /opt/terminaltables </font></span><span style="background-color:#4E9A06"><font color="#3465A4"></font></span><span style="background-color:#4E9A06"><font color="#2E3436">  master </font></span><font color="#4E9A06"></font> 
</pre>

even updating it i get an terminaltables error:
<pre><span style="background-color:#2E3436"> </span><span style="background-color:#2E3436"><font color="#C4A000">⚡ </font></span><span style="background-color:#3465A4"><font color="#2E3436"> ~/Desktop/rosee </font></span><font color="#3465A4"></font> <font color="#4E9A06">rtfm</font> -u        
<font color="#FCE94F"><b>[WARNING]: </b></font>Unable to have pretty output,  Please &apos;pip install terminaltables&apos; or remove these lines :)
<font color="#8AE234"><b>[OK]: </b></font>This may appear to hang. Run with debug to get more info
<font color="#8AE234"><b>[OK]: </b></font>Program version information :
0.9.8
 Added A way of fixing typo&apos;s in the database 
</pre>

**Comment by leostat** [comment]
It looks like the version of RTFM is out of date, it should be 1.0.1, But its also meant to tell you that there is an update! 0.9.8 was in python 2.7 whereas 1.0.1 is in python 3 and should work (hopefully)

I will try to figure out why its not telling you that there is a python three version shortly :)

**Comment by rowbot1** [comment]
thats it, ty
